language: ruby
bundler_args: --retry=3 --jobs=3
cache: bundler
rvm:
  - 2.3.1
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake
